version: '3.7'

services:
  php:
    image: registry.cn-hangzhou.aliyuncs.com/jam/lnmp-docker:1.0
    volumes:
      - ./src:/var/www/html
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    depends_on:
      - mysql    # PHP 服务依赖于 MySQL 服务
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql #把容器的数据文件夹映射到 ./mysql/data
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'u_root_password'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
