version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql    # PHP 服务依赖于 MySQL 服务
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql #把容器的数据文件夹映射到 ./mysql/data
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ZpbWT3nXtW3sPFxjGH*&&*!@#
      MYSQL_DATABASE: aitooth
      MYSQL_USER: aitooth
      MYSQL_PASSWORD: ZpbWT3nXtW3sPFxj
    ports:
      - "13306:3306"
    networks:
      - app-network

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8899:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
